server:
  port: 8802

spring:
  application:
    name: service-eureka
eureka:
  instance:
    hostname: eureka02
  client:
    service-url:
      defaultZone: http://eureka01:8801/eureka
    fetch-registry: false
