server:
  port: 8888

spring:
  application:
    name: service-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
    fetch-registry: false
    register-with-eureka: false
