server:
  port: 8700
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          # 这里填写的是本地仓库地址，远程仓库直接填写远程仓库地址 http://git...
          uri: file://${user.home}/Desktop/spring-cloud-config-repo
          # 默认分支设定为你自己本地或是远程分支的名称
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://eureka02:8801/eureka, http://eureka02:8802/eureka