server:
  port: 8500

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: borrow-service
          uri: lb://service-borrow
          predicates:
            - Path=/borrow/**
        - id: book-service
          uri: lb://service-book
          predicates:
            - Path=/book/**
          filters:
            - AddRequestHeader=Test, HelloWorld!

eureka:
  client:
    service-url:
      defaultZone: http://eureka02:8801/eureka, http://eureka02:8802/eureka